steps:

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/api-fetcher-cb', '.']

  # Push Docker image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/api-fetcher-cb']

  # Apply Terraform configuration
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    dir: 'terraform'

  - name: 'hashicorp/terraform:latest'
    args: ['apply', '-auto-approve']
    dir: 'terraform'
    
# Specify the custom service account
serviceAccount: "terraform-run-sa@constant-host-448316-e1.iam.gserviceaccount.com"

# Specify a logs' bucket
logsBucket: "gs://cloud-build-ci-cd-logs"