name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ "main" ]

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Python script
        run: python3 app.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

  build-and-push-docker:
    needs: fetch-and-store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/${{ vars.GCP_PROJECT_ID }}/api-fetcher-cb:latest .
          docker push gcr.io/${{ vars.GCP_PROJECT_ID }}/api-fetcher-cb:latest

  deploy-to-cloud-run:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        working-directory: ./terraform  # Change to Terraform dir
        run: terraform init
      - name: Terraform Apply
        working-directory: ./terraform  # Change to Terraform dir
        run: terraform apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
